# Generated by Django 6.1 on 2026-08-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("users", "0002_shopsettings")]

    operations = [
        migrations.RemoveField(
            model_name="shopsettings",
            name="currency",
        ),
    ]
