# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("inventory", "0002_product_is_service")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional image URL for the POS category card.",
            ),
        ),
    ]
