# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("inventory", "0003_category_image_url")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, help_text="Optional product image URL."),
        ),
    ]
